# Generated by Django 4.2 on 2023-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
